version: "3.8"

volumes:
  vol-emqx-data:
    name: foo-emqx-data
  vol-emqx-etc:
    name: foo-emqx-etc
  vol-emqx-log:
    name: foo-emqx-log

services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      TZ: "America/CostaRica"

      MONGO_INITDB_ROOT_USERNAME: kiot
      MONGO_INITDB_ROOT_PASSWORD: 9ab60d17
      
    volumes:
      - ./mongodata:/data/db
    ports:
      - 27017:27017


  emqx:

    container_name: emqx
    image: emqx/emqx:4.2.3
    restart: always
    ports:
      - 18083:18083
      - 8083:8083
    volumes:
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-etc:/opt/emqx/etc
      - vol-emqx-log:/opt/emqx/log

    links: 
      - mongo
      
    environment: 
      
      EMQX_NAME: kIoT
      EMQX_HOST: 127.0.0.1
      TZ: "America/Costa Rica"
      # DEFAULT DASH PASS
      EMQX_DASHBOARD__DEFAULT_USER__PASSWORD: "9ab60d17"

      EMQX_LISTENER__TCP__EXTERNAL__MAX_CONNECTIONS: 1000